command-usage:
  - "&6_____________.[ &2Custom Emojis &6]._____________"
  - "&b/CustomEmojis reload &eReloads the configuration"
  - "&b/emojis &eOpens the gui with all the emojis"

reload-success: "&2&lCustomEmojis &8» &fhas been reloaded &asuccessfully"

permission:
  command: customemojis.use

Gui:
  open-message: "&2&lCustomEmojis &8» &fOpening GUI"
  # NOT FUNCTIONAL:
  Title: "Emojis (Page {page}/{totalPages})"
  BorderItemName: " "
  EmojiItem:
    Name: "Emoji: {emojiName}"
    Lore:
      - "Before: {emojiName}"
      - "After: {emojiReplaced}"
  PreviousPageButton:
    Name: "Previous Page"
  NextPageButton:
    Name: "Next Page"
  HeaderItem:
    Name: "Emoji List"
    Lore:
      - "Browse through the emoji list!"
      - "Page {page} of {totalPages}"

Emojis:
  - ":skull:->&4☠&r"
  - "<3->&c❤&r"
  - ":star:->&6✮&r"
  - ":yes:->&a✔&r"
  - ":no:->&c✖&r"
  - ":java:->&6☕&r"
  - ":arrow:->&e➜&r"
  - ":shrug:->&e¯\\_(ツ)_/¯&r"
  - ":tableflip:->&c(╯°□°）╯&7 ┻━┻&r"
  - "o/->&d( ﾟ◡ﾟ)/&r"
  - ":123:->&a1&e2&c3&"
  - ":totem:->&b☉&e_&b☉&r"
  - ":typing:->&e✎&6...&r"
  - ":maths:->&a√&e(&aπ+x&e)&a=&cL&"
  - ":snail:->&e@&a'&e-&a'&r"
  - ":thinking:->&6(&a0&6.&ao&c?&6)&r"
  - ":gimme:->&b༼つ◕_◕༽つ&r"
  - ":wizard:->&e(&b'&e-&b'&e)⊃━&c☆ﾟ.&d*･｡ﾟ&"
  - ":pvp:->&e⚔&r"
  - ":peace:->&b✌&r"
  - ":oof:->&c&lOOF&r"
  - ":puffer:->&e<('O')>&r"
  - ":yey:->&aヽ (◕◡◕) ﾉ&r"
  - ":cat:->&e= &b＾● ⋏ ●＾ &e=&r"
  - ":dab:->&d<&eo&d/&r"
  - ":dj:->&9ヽ&5(&d⌐&c■&6_&e■^b)&3ノ&9♬&r"
  - ":snow:->&b☃&r"
  - "^_^->&a^_^&r"
  - "h/->&eヽ(^◇^*)/&r"
  - "^-^->&a^-^&r"
  - ":sloth:->&6(&8・&6⊝&8・&6)&r"
  - ":cute:->&e(&a✿&e◠‿◠)&r"
  - ":dog:->&6(ᵔᴥᵔ)&r"